### PR TITLE
update copyright headers and dependencies

### PR DESCRIPTION
**Pull request by wdpypere**

### CODE REVIEW

**Comment by boegel** [comment]
@wdpypere tests fail?

**Comment by wdpypere** [comment]
@boegel yes, several things fail. like pulling the python 3.6 image for the github tests.

**Comment by boegel** [comment]
@wdpypere For Python 2.7 on Jenkins:
```
  File "/var/lib/jenkins/jobs/hpcugent_github.com/jobs/vsc-install/branches/PR-210/workspace/.eggs.py2/singledispatch-4.0.0-py2.7.egg/singledispatch/__init__.py", line 164
    raise RuntimeError(f"Ambiguous dispatch: {match} or {t}")
                                                           ^
SyntaxError: invalid syntax
ERROR: InvocationError for command /var/lib/jenkins/jobs/hpcugent_github.com/jobs/vsc-install/branches/PR-210/workspace/.tox/py27/bin/python setup.py test (exited with code 1)
```

So we need to avoid `singledispatch` 4.0.0 (released just 6 hours ago)

For GitHub, we'll probably need to stick to Ubuntu 20.04 by using `runs-on: ubuntu-20.04` instead of `runs-on: ubuntu-latest` in `.github/workflows/unittest.yml` if we want to keep testing with Python 3.6 there

**Comment by wdpypere** [comment]
@boegel tests and dependencies fixed.

**Review by boegel — APPROVED** [review]
lgtm

**Pull request merged**
