### PR TITLE
add tests for bad whitespace

### PR DESCRIPTION
**Pull request by wdpypere**
This is just a suggestion, but I know I make a lot of these kinds of mistakes.

### CODE REVIEW

**Comment by stdweird** [comment]
we should first try the impact of this on other repos like vsc-base. can you locally install and do a `python setup.py test` on vsc-base?

**Comment by wdpypere** [comment]
the tests of vsc-base fail but on the linting @jgtimmer added: e.g.:  about 20 error of line too long.
no messages about bad whitespace.

**Comment by stdweird** [comment]
@wdpypere thx
@JensTimmerman i'm ok with merging this

**Comment by JensTimmerman** [comment]
jenkins test this please

**Comment by JensTimmerman** [comment]
jenkins add to whitelist

**Pull request merged**
