### PR TITLE
Add vsc_release command to show what needs to be done

### PR DESCRIPTION
**Pull request by stdweird**
some smart person might actually make this do stuff instead of just print

### CODE REVIEW

**Comment by JensTimmerman** [comment]
don't we need a clusterbuildrpm and bc step here aswell?

**Comment by stdweird** [comment]
clusterbuildrpm might be a good thing to have, but could be complex.

**Comment by stdweird** [comment]
@JensTimmerman tested with vsc-utils 1.7.3 release

**Comment by stdweird** [comment]
hmmm, github releases can't be used as download urls. they do not have the vsc.install injection like pypi sdist, and also unpack totally wrong (`vsc-utils-1.7.3` tag unpacks in `vsc-utils-vsc-utils-1.7.3`). i removed the release on github

**Pull request merged**
